name: influxdb3
services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: ./influxdb3/core/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ./influxdb3/core/plugins
        target: /var/lib/influxdb3/plugins
  python-tests:
    image: python:3.13-alpine
    command:
      - /bin/sh
      - -c
      - |
        pip install -r /test/requirements.txt
        python3 -m pytest -v /test/influxdb_test.py
    volumes:
      - type: bind
        source: ./test
        target: /test
    environment:
      - INFLUXDB_URL=http://influxdb3-core:8181
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    depends_on:
      - influxdb3-core